unbind r
bind r source-file ~/.tmux.conf
set-option -g status-position top
set -g status-right ""
set -g xterm-keys on

set -g prefix C-s
set -g mouse on
setw -g mode-keys vi

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind "'" split-window -h
bind -n C-space copy-mode
bind M-, swap-window -t -1 \; select-window -t -1
bind M-. swap-window -t +1 \; select-window -t +1
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi v if-shell -F "#{selection_active}" "send-keys -X clear-selection" "send-keys -X begin-selection"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'
run '~/.tmux/plugins/tpm/tpm'

set -g @ctp_bg "#202020"
set -g @ctp_surface_1 "#1c1c1c"
set -g @ctp_fg "#858585"
set -g @ctp_mauve "#121212"
set -g @ctp_crust "#ffffff"

set -gF status-style "bg=#{@ctp_bg},fg=#{@ctp_fg}"
set -gF window-status-format "#[bg=#{@ctp_surface_1},fg=#{@ctp_fg}] ##I ##T "
set -gF window-status-current-format "#[bg=#{@ctp_mauve},fg=#{@ctp_crust}] ##I ##T "
