# Window settings
window_padding_width 2
initial_window_width 85c
initial_window_height 21c
placement_strategy top-left
confirm_os_window_close 0

# Bell effect
enable_audio_bell no
visual_bell_duration 0.0

# Font settings
font_family JetBrainsMono Nerd Font Normal
font_size 12.0

# Cursor settings
cursor_shape beam

# Colors
# ackground and foreground colors
background #0d0e0f
foreground #989c9b

# Cursor colors
cursor #d0d0d0
cursor_text_color #000000

# Selection colors
selection_foreground #757575
selection_background #424242

# Background and foreground
background #101010
foreground #c0c0c0

color0 #1a1a1a
color8 #4a4a4a
color1 #8b5555
color9 #a86060
color2 #557a55
color10 #6a9a6a
color3 #8b7e55
color11 #a89a6a
color4 #55657a
color12 #6a80a8
color5 #7a5577
color13 #a06a9a

color6 #557a7a
color14 #6a9a9a
color7 #c0c0c0
color15 #e0e0e0
